#pragma once

#ifdef KISAK_MP
#include "client_mp/client_mp.h"
#elif KISAK_SP
#include "client/client.h"
#elif defined(KISAK_RADIANT)
#include <cstdint>
struct vidConfig_t // sizeof=0x30 — subset needed by r_init; matches client_mp.h layout
{
    uint32_t sceneWidth;
    uint32_t sceneHeight;
    uint32_t displayWidth;
    uint32_t displayHeight;
    uint32_t displayFrequency;
    int32_t  isFullscreen;
    float    aspectRatioWindow;
    float    aspectRatioScenePixel;
    float    aspectRatioDisplayPixel;
    uint32_t maxTextureSize;
    uint32_t maxTextureMaps;
    bool     deviceSupportsGamma;
    // 3 padding bytes
};
#endif

#include "r_gfx.h"
#include "r_bsp.h"
#include "r_rendercmds.h"
#include "r_image.h"
#include "r_fog.h"

#ifdef __SWITCH__
// The vendored d3d9-headers provide the windef handle types (HWND__,
// _D3DPRESENT_PARAMETERS_) the renderer declarations use on Horizon.
#include <windows.h>
#else
#include <Windows.h>
#endif
#include <d3d9.h>

enum GfxRenderer : __int32
{                                       // ...
    GFX_RENDERER_SHADER_2 = 0x0,
    GFX_RENDERER_SHADER_3 = 0x1,
    GFX_RENDERER_COUNT = 0x2,
    GFX_RENDERER_UNSPECIFIED = 0x2,
};

struct GfxAssets // sizeof=0x4
{                                       // ...
    IDirect3DQuery9 *pixelCountQuery;   // ...
};

#define MAX_TOTAL_ENT_COUNT 0x1000

struct GfxConfiguration // sizeof=0x30
{                                       // ...
    uint32_t maxClientViews;        // ...
    uint32_t entCount;              // ...
    uint32_t entnumNone;            // ...
    uint32_t entnumOrdinaryEnd;     // ...
    int32_t threadContextCount;             // ...
    int32_t critSectCount;
    const char *codeFastFileName;       // ...
    const char *uiFastFileName;         // ...
    const char *commonFastFileName;     // ...
    const char *localizedCodeFastFileName; // ...
    const char *localizedCommonFastFileName; // ...
    const char *modFastFileName;        // ...
};

struct GfxMetrics // sizeof=0x28
{                                       // ...
    uint16_t cubemapShotRes;    // ...
    uint16_t cubemapShotPixelBorder; // ...
    uint16_t feedbackWidth;
    uint16_t feedbackHeight;
    bool hasAnisotropicMinFilter;       // ...
    bool hasAnisotropicMagFilter;       // ...
    // padding byte
    // padding byte
    int maxAnisotropy;                  // ...
    int maxClipPlanes;                  // ...
    bool hasHardwareShadowmap;          // ...
    // padding byte
    // padding byte
    // padding byte
    _D3DFORMAT shadowmapFormatPrimary;  // ...
    _D3DFORMAT shadowmapFormatSecondary; // ...
    MaterialTechniqueType shadowmapBuildTechType; // ...
    uint8_t shadowmapSamplerState; // ...
    bool slopeScaleDepthBias;           // ...
    bool canMipCubemaps;                // ...
    bool hasTransparencyMsaa;           // ...
};

struct GfxWindowParms // sizeof=0x28
{                                       // ...
    HWND__ *hwnd;                       // ...
    int hz;                             // ...
    bool fullscreen;                    // ...
    // padding byte
    // padding byte
    // padding byte
    int x;                              // ...
    int y;                              // ...
    int sceneWidth;                     // ...
    int sceneHeight;                    // ...
    int displayWidth;                   // ...
    int displayHeight;                  // ...
    int aaSamples;                      // ...
};

struct GfxGammaRamp // sizeof=0x200
{                                       // ...
    uint16_t entries[256];      // ...
};

struct trStatistics_t // sizeof=0x28
{                                       // ...
    int c_indexes;                      // ...
    int c_fxIndexes;                    // ...
    int c_viewIndexes;                  // ...
    int c_shadowIndexes;                // ...
    int c_vertexes;
    int c_batches;                      // ...
    float dc;
    Image_MemUsage c_imageUsage;        // ...
};

struct GfxWorld;
struct __declspec(align(128)) r_global_permanent_t // sizeof=0x2180
{                                       // ...
    Material *sortedMaterials[2048];    // ...
    int needSortMaterials;              // ...
    int materialCount;                  // ...
    GfxImage *whiteImage;               // ...
    GfxImage *blackImage;               // ...
    GfxImage *blackImage3D;             // ...
    GfxImage *blackImageCube;           // ...
    GfxImage *grayImage;                // ...
    GfxImage *identityNormalMapImage;   // ...
    GfxImage *specularityImage;
    GfxImage *outdoorImage;
    GfxImage *pixelCostColorCodeImage;  // ...
    GfxLightDef *dlightDef;             // ...
    Material *defaultMaterial;          // ...
    Material *whiteMaterial;            // ...
    Material *additiveMaterial;         // ...
    Material *pointMaterial;            // ...
    Material *lineMaterial;             // ...
    Material *lineMaterialNoDepth;      // ...
    Material *clearAlphaStencilMaterial; // ...
    Material *shadowClearMaterial;      // ...
    Material *shadowCookieOverlayMaterial; // ...
    Material *shadowCookieBlurMaterial; // ...
    Material *shadowCasterMaterial;     // ...
    Material *shadowOverlayMaterial;    // ...
    Material *depthPrepassMaterial;     // ...
    Material *glareBlindMaterial;       // ...
    Material *pixelCostAddDepthAlwaysMaterial; // ...
    Material *pixelCostAddDepthDisableMaterial; // ...
    Material *pixelCostAddDepthEqualMaterial; // ...
    Material *pixelCostAddDepthLessMaterial; // ...
    Material *pixelCostAddDepthWriteMaterial; // ...
    Material *pixelCostAddNoDepthWriteMaterial; // ...
    Material *pixelCostColorCodeMaterial; // ...
    Material *stencilShadowMaterial;    // ...
    Material *stencilDisplayMaterial;   // ...
    Material *floatZDisplayMaterial;    // ...
    Material *colorChannelMixerMaterial; // ...
    Material *frameColorDebugMaterial;  // ...
    Material *frameAlphaDebugMaterial;  // ...
    GfxImage *rawImage;                 // ...
    GfxWorld *world;                    // ...
    Material *feedbackReplaceMaterial;  // ...
    Material *feedbackBlendMaterial;    // ...
    Material *feedbackFilmBlendMaterial; // ...
    Material *cinematicMaterial;        // ...
    Material *dofDownsampleMaterial;    // ...
    Material *dofNearCocMaterial;       // ...
    Material *smallBlurMaterial;        // ...
    Material *postFxDofMaterial;        // ...
    Material *postFxDofColorMaterial;   // ...
    Material *postFxColorMaterial;      // ...
    Material *postFxMaterial;           // ...
    Material *symmetricFilterMaterial[8]; // ...
    Material *shellShockBlurredMaterial; // ...
    Material *shellShockFlashedMaterial; // ...
    Material *glowConsistentSetupMaterial; // ...
    Material *glowApplyBloomMaterial;   // ...
    int savedScreenTimes[4];            // ...
#ifdef KISAK_RADIANT
    // Editor-only: the CASE_TEXTURE technique (camera draw_mode 4) selects, per world
    // surface, the case-texture GfxImage whose width/height matches the surface's colorMap.
    // R_LoadCaseTextures (case_textures.txt) populates these; R_GetCaseTexture reads them.
    // Appended at the kisak struct's tail (standalone layout — binary offsets irrelevant).
    int caseTextures_count;             // idb r_global_permanent_t+16540
    GfxImage *caseTextures[64];         // idb r_global_permanent_t+16544
#endif
    // LWSS: lots of padding
};

struct VertUsage // sizeof=0x8
{
    int index;
    VertUsage *next;
};

struct MaterialUsage // sizeof=0xC
{                                       // ...
    int memory;
    VertUsage *verts;                   // ...
    Material *material;
};

struct GfxLodRamp // sizeof=0x8
{                                       // ...
    float scale;                        // ...
    float bias;                         // ...
};
struct GfxLodParms // sizeof=0x20
{                                       // ...
    float origin[3];                    // ...
    GfxLodRamp ramp[2];                 // ...
    bool valid;                         // ...
    // padding byte
    // padding byte
    // padding byte
};

struct __declspec(align(8)) r_globals_t // sizeof=0x8310
{                                       // ...
    GfxViewParms identityViewParms;     // ...
    bool inFrame;                       // ...
    bool registered;                    // ...
    bool forbidDelayLoadImages;
    bool ignorePrecacheErrors;
    float viewOrg[3];                   // ...
    float viewDir[3];                   // ...
    uint32_t frontEndFrameCount;    // ...
    int totalImageMemory;
    Material *materialHashTable[2048];  // ...
    MaterialUsage materialUsage[2048];  // ...
    GfxFog fogSettings[FOG_COUNT];
    int fogIndex;                       // ...
    GfxColor color_axis;                // ...
    GfxColor color_allies;              // ...
    int team;                           // ...
    trStatistics_t *stats;              // ...
    GfxLodParms lodParms;               // ...
    GfxLodParms correctedLodParms;      // ...
    bool hasAnyImageOverrides;          // ...
    bool useSunLightOverride;           // ...
    bool useSunDirOverride;             // ...
    bool useSunDirLerp;                 // ...
    float sunLightOverride[3];          // ...
    float sunDirOverride[3];            // ...
    float sunDirOverrideTarget[3];      // ...
    int sunDirLerpBeginTime;            // ...
    int sunDirLerpEndTime;              // ...
    GfxScaledPlacement identityPlacement; // ...
    const GfxViewParms *debugViewParms; // ...
    int endTime;                        // ...
    bool distortion;                    // ...
    bool drawWorld;                     // ...
    bool drawSModels;                   // ...
    bool drawXModels;                   // ...
    bool drawBModels;                   // ...
    // padding byte
    // padding byte
    // padding byte
    const char *codeImageNames[27];     // ...
    uint32_t viewInfoCount;         // ...
    int sunShadowFull;                  // ...
    float sunShadowmapScale;            // ...
    float sunShadowmapScaleNum;         // Numerator of shadow scale
    uint32_t sunShadowSize;         // Shadow Texture Size
    float sunShadowPartitionRatio;      // How far away the partitions are (usually 4x)
    int drawSunShadow;                  // ...
    int skinnedCacheReachedThreshold;   // ...
    float waterFloatTime;               // ...
    // padding byte
    // padding byte
    // padding byte
    // padding byte
};

struct GfxWindowTarget // sizeof=0x10
{                                       // ...
    HWND__ *hwnd;                       // ...
    IDirect3DSwapChain9 *swapChain;     // ...
    int width;                          // ...
    int height;                         // ...
};

// R_MAX_WINDOWS — the device's window/swap-chain capacity. The shipping CoD3 game is
// single-window (implicit swap chain only). The CoD4Radiant editor cycles ONE D3D9
// device across up to five child views (Camera / XY / Z / Texture / LayeredMaterial),
// each its own swap chain — the IDB's DxGlobals.windows is GfxWindowTarget[5] and
// R_CreateSwapChains/R_CreateWindow assert windowCount <= 5. KISAK_RADIANT-only: this
// is an engine-struct dimension change, so it is gated (SP/MP keep windows[1]).
#ifdef KISAK_RADIANT
#define R_MAX_WINDOWS 5
#else
#define R_MAX_WINDOWS 1
#endif

struct __declspec(align(8)) DxGlobals // sizeof=0x2CE0 (game) / 0x2D20 (radiant: windows[5])
{                                       // ...
    HINSTANCE__ *hinst;
    IDirect3D9 *d3d9;                   // ...
    IDirect3DDevice9 *device;           // ...
    uint32_t adapterIndex;          // ...
    bool adapterNativeIsValid;          // ...
    // padding byte
    // padding byte
    // padding byte
    int adapterNativeWidth;             // ...
    int adapterNativeHeight;            // ...
    int adapterFullscreenWidth;         // ...
    int adapterFullscreenHeight;        // ...
    _D3DFORMAT depthStencilFormat;      // ...
    uint32_t displayModeCount;      // ...
    _D3DDISPLAYMODE displayModes[256];  // ...
    const char *resolutionNameTable[257]; // ...
    const char *refreshRateNameTable[257]; // ...
    char modeText[5120];                // ...
    IDirect3DQuery9 *fencePool[8];      // ...
    uint32_t nextFence;             // ...
    int gpuSync;                        // ...
    _D3DMULTISAMPLE_TYPE multiSampleType; // ...
    uint32_t multiSampleQuality;    // ...
    int sunSpriteSamples;               // ...
    IDirect3DSurface9 *singleSampleDepthStencilSurface; // ...
    bool deviceLost;                    // ...
    bool inScene;                       // ...
    // padding byte
    // padding byte
    int targetWindowIndex;              // ...
    int windowCount;                    // ...
    GfxWindowTarget windows[R_MAX_WINDOWS]; // [1] game / [5] radiant editor (multi-window)
    int flushGpuQueryCount;             // ...
    IDirect3DQuery9 *flushGpuQuery;     // ...
    unsigned __int64 gpuSyncDelay;      // ...
    unsigned __int64 gpuSyncStart;      // ...
    unsigned __int64 gpuSyncEnd;        // ...
    bool flushGpuQueryIssued;           // ...
    // padding byte
    // padding byte
    // padding byte
    _D3DTEXTUREFILTERTYPE linearNonMippedMinFilter;
    _D3DTEXTUREFILTERTYPE linearNonMippedMagFilter;
    _D3DTEXTUREFILTERTYPE linearMippedMinFilter;
    _D3DTEXTUREFILTERTYPE linearMippedMagFilter;
    _D3DTEXTUREFILTERTYPE anisotropicMinFilter;
    _D3DTEXTUREFILTERTYPE anisotropicMagFilter;
    int linearMippedAnisotropy;
    int anisotropyFor2x;
    int anisotropyFor4x;
    int mipFilterMode;
    uint32_t mipBias;               // ...
    IDirect3DQuery9 *swapFence;         // ... (unused: the swap wait is native, RB_BackendTimeout)
    // deko9 native frame pacing: the frame the GPU sync waits for
    // (R_InsertGpuFence), replacing dx.flushGpuQuery's event query.
    uint64_t gpuSyncFrame;
    // padding byte
    // padding byte
    // padding byte
    // padding byte
};

struct GfxGlobals // sizeof=0x10
{                                       // ...
    bool haveThreadOwnership;           // ...
    bool startedRenderThread;           // ...
    bool isRenderingRemoteUpdate;       // ...
    // padding byte
    volatile int screenUpdateNotify;    // ...
    volatile int remoteScreenUpdateNesting; // ...
    int backEndFrameCount;              // ...
};

void __cdecl TRACK_r_init();
const char *__stdcall DXGetErrorDescription9A(int a1);
void __cdecl R_SyncGpu(int(__cdecl *WorkCallback)(unsigned __int64));
bool __cdecl R_IsUsingAdaptiveGpuSync();
void __cdecl  R_FatalInitError(const char *msg);
void __cdecl  R_FatalLockError(HRESULT hr);
const char *__cdecl R_ErrorDescription(HRESULT hr);
void __cdecl R_SetColorMappings();
void __cdecl R_CalcGammaRamp(GfxGammaRamp *gammaRamp);
void __cdecl R_GammaCorrect(uint8_t *buffer, int bufSize);
void __cdecl SetGfxConfig(const GfxConfiguration *config);
void __cdecl R_InitThreads();
void __cdecl R_ShutdownStreams();
void __cdecl R_ShutdownMaterialUsage();
void __cdecl R_Shutdown(int destroyWindow);
void R_ShutdownDirect3D();
void R_ReleaseForShutdownOrReset();
void __cdecl R_UnloadWorld();
void __cdecl R_BeginRegistration(vidConfig_t *vidConfigOut);
void R_Init();
#ifdef __SWITCH__
// Synchronize the deko3d backend's submission/GPU lifetime before Switch
// tears down or reloads renderer-owned assets. This is separate from
// R_SyncRenderThread(), which only drains the engine's frontend/backend
// command handoff.
void R_SwitchWaitForGpuIdle();
#endif
#ifdef KISAK_RADIANT
// Editor multi-window renderer bring-up (implementation at end of r_init.cpp).
char __cdecl R_InitRendererForWindow(HWND hWnd);
HWND __cdecl R_CreateSwapChains(int hz, GfxWindowParms *wnd, int sharedHandle);
char __cdecl R_BeginRegistration_R_InitHardware(GfxWindowParms *wnd);
// Editor per-window render-target / device-test path (CXYWnd::OnPaint pipeline).
// Implementations at end of r_init.cpp; R_SortMaterials lives in radiant/r_ed_scene.cpp.
// (R_RecoverLostDevice is already declared above — kisak ships the CoD3 recovery.)
char __cdecl R_TestDevice();
void __cdecl R_SetupTargetWindow(int windowIndex);
// Editor renderer R_Init (IDB 0x500820): registers dvars/cmds + creates the D3D9
// object, but does NOT create a game window/device (deferred to R_InitRendererForWindow).
// Distinct from kisak's game R_Init, which creates its own window via R_InitGraphicsApi.
void __cdecl R_InitEditor();
char __cdecl R_SetupRendertarget_CheckDevice(HWND__ *hwnd);
// Non-asserting test for "is this hwnd a registered render target with a live swap chain".
// (KISAK_RADIANT — used by CCamWnd::OnPaint to skip painting a window the renderer never
// registered, e.g. the dead Dynamic-Lighting popup, instead of tripping the CheckDevice
// "invalid hwnd" assert.)
bool __cdecl R_IsRegisteredRenderWindow(HWND__ *hwnd);
void __cdecl R_CheckTargetWindow(HWND__ *hwnd);
void __cdecl R_SortMaterials();
// Editor per-window resize (IDB 0x501260): re-creates the window's swap chain at the new
// size so Present is pixel-correct (no stretch). Called from each view's OnSize.
void __cdecl R_Hwnd_Resize(HWND__ *hwnd, int width, int height);
#endif
void R_InitGraphicsApi();
void R_InitSystems();
char __cdecl R_PreCreateWindow();
void __cdecl R_StoreDirect3DCaps(uint32_t adapterIndex);
void __cdecl R_GetDirect3DCaps(uint32_t adapterIndex, _D3DCAPS9 *caps);
void __cdecl R_SetShadowmapFormats_DX(uint32_t adapterIndex);
uint32_t __cdecl R_ChooseAdapter();
void __cdecl Sys_HideSplashWindow();
void __cdecl Sys_DestroySplashWindow();
char __cdecl R_CreateGameWindow(GfxWindowParms *wndParms);
char __cdecl R_InitHardware(const GfxWindowParms *wndParms);
void __cdecl R_StoreWindowSettings(const GfxWindowParms *wndParms);
void R_InitGamma();
char __cdecl R_CreateForInitOrReset();
IDirect3DQuery9 *__cdecl RB_HW_AllocOcclusionQuery();
char __cdecl R_CreateDevice(const GfxWindowParms *wndParms);
void __cdecl R_SetD3DPresentParameters(_D3DPRESENT_PARAMETERS_ *d3dpp, const GfxWindowParms *wndParms);
void __cdecl R_SetupAntiAliasing(const GfxWindowParms *wndParms);
HRESULT __cdecl R_CreateDeviceInternal(HWND__ *hwnd, uint32_t behavior, _D3DPRESENT_PARAMETERS_ *d3dpp);
int __cdecl R_GetDeviceType();
void __cdecl R_SetWndParms(GfxWindowParms *wndParms);
void R_Register();
void R_InitGlobalStructs();
void __cdecl R_EndRegistration();
void __cdecl R_TrackStatistics(trStatistics_t *stats);
void __cdecl R_UpdateTeamColors(int team, const float *color_allies, const float *color_axis);
void __cdecl R_ConfigureRenderer(const GfxConfiguration *config);
void __cdecl R_ComErrorCleanup();
bool R_CheckLostDevice();
void __cdecl R_MakeDedicated(const GfxConfiguration *config);

void __cdecl R_UpdateGpuSyncType();

int R_IsHiDef();

void R_MaterializeAllImages();
// Required retail resources: reject actual substitutions, permit authored stock images.
bool R_MaterializeImageStrict(GfxImage *image);

extern DxGlobals dx;
extern r_global_permanent_t rgp;
extern int g_disableRendering;
extern r_globals_t rg;
extern vidConfig_t vidConfig;
extern GfxConfiguration gfxCfg;
extern GfxAssets gfxAssets;
extern GfxGlobals r_glob;
extern GfxMetrics gfxMetrics;
extern bool g_allocateMinimalResources;
